version: "3.9"
services:
  db:
    container_name: "db"
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=linx-cart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    
  api:
    container_name: "api"
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on: 
      - db
      - redis
    links: 
      - db
      - redis
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=linx-cart          
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/app
    command: >
      sh -c "
      yarn typeorm migration:run
      && yarn build
      && yarn start
      "
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
